apiVersion: apps/v1
kind: Deployment
metadata:
  name: careerwry-edge
  labels:
    app: careerwry-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: careerwry-edge
  template:
    metadata:
      labels:
        app: careerwry-edge
    spec:
      containers:
        - name: careerwry-edge
          image: careerwry-edge
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9000
          env:
            - name: MEMBER_SERVICE_URL
              value: http://careerwry-member
