apiVersion: v1
kind: Service
metadata:
  name: careerwry-edge
  labels:
    app: careerwry-edge
spec:
  type: ClusterIP
  selector:
    app: careerwry-edge
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000